name 'instana-agent'
maintainer 'Instana Inc.'
maintainer_email 'ops@instana.com'
license 'Apache-2.0'
description 'Installs/Configures instana-agent'
version '1.0.14'
source_url 'https://github.com/instana/instana-agent-chef'
issues_url 'https://github.com/instana/instana-agent-chef/issues'
chef_version '>= 12.20.3'
depends 'zypper', '= 0.4.0'
supports 'ubuntu', '= 16.04'
supports 'ubuntu', '= 14.04'
supports 'centos', '= 6.0'
supports 'centos', '= 7.0'
supports 'debian', '= 7.0'
supports 'redhat', '= 6.0'
supports 'redhat', '= 7.0'
supports 'suse', '= 12.0'
supports 'amazon'
